### ISSUE TITLE
Geef een totaalprijs per stuk voor het aantal bestelde producten

### ISSUE THREAD

**Issue by Kwinnieprince** [Kwinnieprince/webshopTesting#2]
voor het aantal bestelde producten moet een totaalprijs staan per product.
Deze story kan deftig geïmplementeerd worden als #1 is afgewerkt
 **Mockup**
<img width="1792" alt="schermafbeelding 2018-11-29 om 12 14 56" src="https://user-images.githubusercontent.com/7886884/49218631-3f44fb80-f3d1-11e8-86ee-2aa8ec1d6951.png">

**Comment by ThomasVermeersch** [comment]
ik ben klaar jonges en meisjes
